const ACTIONS = {
  INITIAL: 'INITIAL',
  UPDATE_ASKS: 'UPDATE_ASKS',
  DELETE_ASKS: 'DELETE_ASKS',
  UPDATE_BIDS: 'UPDATE_BIDS',
  DELETE_BIDS: 'DELETE_BIDS',
  REQUEST_STARTED: 'REQUEST_STARTED',
  REQUEST_SUCCESS: 'REQUEST_SUCCESS',
  REQUEST_ERROR: 'REQUEST_ERROR',
};

export default ACTIONS;
